### PR TITLE
Proper tidy up and sorted mask loading efficiency in classifier

### PR DESCRIPTION
**Pull request by nthndy**

### CODE REVIEW

**Comment by quantumjot** [comment]
> still work to do regarding the finessing of classifier and data io but now the whole pipeline is much tidier

Nice! Do you want to merge or keep working on it?

**Comment by nthndy** [comment]
Just added a few more commits that should improve 2-channel/2-population functionality buttttt i think maybe we should create separate versions for single population and 2-population? idk what do you think? im envisioning a simple, single population version in the main repo then tucked away in another folder can be a more complex competition segment-classify-track pipeline.

**Comment by nthndy** [comment]
but feel free to merge what i just pushed as it's way easier to use the classifier now (also does it correctly with bf input)

**Comment by quantumjot** [comment]
sounds good - will merge, and assume everything works correctly!

**Review by quantumjot — APPROVED** [review]

**Comment by nthndy** [comment]
Yes it does, however the octolite loader pr i just submitted needs merging if we want to use the multichannel segmentation input, if not i can just change to load masks without using octolite.

**Pull request merged**
